# Java Gradle CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-java/ for more details
#
version: 2.1

jobs:
  build:
    docker:
      # specify the version you desire here
      - image: gradle:6-jdk11-focal

      # Specify service dependencies here if necessary
      # CircleCI maintains a library of pre-built images
      # documented at https://circleci.com/docs/2.0/circleci-images/
      # - image: circleci/postgres:9.4

    working_directory: ~/repo
    environment:
      # Customize the JVM maximum heap limit
      JVM_OPTS: -Xmx3200m
      TERM: dumb

    steps:
      - checkout

      # Download and cache dependencies
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "build.gradle" }}
            # fallback to using the latest cache if no exact match is found
            - v1-dependencies-

      - run: gradle dependencies

      - save_cache:
          paths:
            - ~/.gradle
          key: v1-dependencies-{{ checksum "build.gradle" }}

      - run: scripts/build_and_run.sh

      - when:
          condition: "<<pipeline.git.tag>>"
          steps:
            - run: mkdir -p workspace
            - run: mv build/libs/*.jar workspace/
            - persist_to_workspace:
                root: workspace
                paths: wealthdraft-<<pipeline.git.tag>>.jar

  publish-github-release:
    docker:
      - image: cimg/go:1.15
    steps:
      - attach_workspace:
          at: ./workspace
      - run:
          name: "Publish JAR to release on GitHub"
          command: |
            go get github.com/tcnksm/ghr
            ghr -t ${GITHUB_TOKEN} -u ${CIRCLE_PROJECT_USERNAME} -r ${CIRCLE_PROJECT_REPONAME} -c ${CIRCLE_SHA1} <<pipeline.git.tag>> ./workspace/

workflows:
  main:
    jobs:
      - build:
          filters:
            branches:
              # No need to build these - we only care about PR (non-master/develop) and tag builds
              ignore:
                - master
                - develop
            # Build tags in preparation for publishing a Github release
            tags: 
              only: /^[0-9]+\.[0-9]+\.[0-9]+$/
      - publish-github-release:
          context:
            - wealthdraft_release_publisher
          requires:
            - build
          filters:
            branches:
              ignore: /.*/
            tags: 
              only: /^[0-9]+\.[0-9]+\.[0-9]+$/
