/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package com.strangegrotto;

public class Main {
    private static final String SUM_LINE = "----------------------------------------------";
    private static final int FAILURE_EXIT_CODE = 1;

    public static void main(String[] args) {
        System.out.println(new Main().getGreeting());
    }
}
